syntax = "proto3";

option java_package = "com.dd.workoutapp";
option java_multiple_files = true;

message ExerciseData {
  string id = 1;
  string type = 2;
  string weight = 3;
  string reps = 4;
  string sets = 5;
}

message LoggedExerciseData {
  string type = 1;
  string weight = 2;
  string date = 3;
}

message WorkoutData {
  string id = 1;
  string name = 2;
  repeated ExerciseData exercises = 3;
}

message WorkoutDataList {
  repeated WorkoutData workouts = 1;

  repeated LoggedExerciseData loggedExercises = 2;

  map<string, WorkoutData> weekMap = 3;
}